### ISSUE TITLE
Add Super Linter GitHub Action

### ISSUE THREAD

**Issue by coliff** [trimble-oss/website-modus-react-bootstrap.trimble.com#210]
I know we already have a lot of linting and testing things - but I think it could be a good idea to add this GitHub Action too:
[github/super-linter](https://github.com/github/super-linter)

The reason being is that it can catch bugs/issues with some things [you might not think about such as YML, XML, JSON formatting issues and many others](https://github.com/github/super-linter#supported-linters). We can set it to disable (not run) on things we test elsewhere (e.g. CSS and JS).

It's free to use and by GitHub - I use it on all my open source projects and find it really useful. It even checks GitHub Actions workflows for issues!

The config would be something like:

```yml
name: Lint Code Base

on:
  push:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAVASCRIPT_DEFAULT_STYLE: prettier
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_EDITORCONFIG: false
          VALIDATE_HTML: false
          VALIDATE_MARKDOWN: false
```
